# Generated by Django 4.2 on 2023-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('etsy_link', models.CharField(default='https://www.etsy.com/shop/FitzPrintsgb', max_length=1000)),
                ('source_link', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('print_time', models.IntegerField()),
                ('filament_used', models.IntegerField()),
                ('filament_cost', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
    ]
