# Generated by Django 4.2 on 2023-04-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_filament_used_alter_product_print_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
