# Generated by Django 4.2 on 2023-05-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_filament_rename_filament_cost_product_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField()),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filament')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
