# Generated by Django 4.2 on 2023-05-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filament_cost',
            field=models.FloatField(default=6.2),
            preserve_default=False,
        ),
    ]
