# Generated by Django 4.2 on 2023-05-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
